Algoritmo "exercicio5"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
Var
   a,b,aux: inteiro

Inicio
      escreval("Informe o valor de A:")
      leia(a)
      escreval("Informe o valor de B:")
      leia(b)
      aux:=a
      a:=b
      b:=aux
      //algoritmo de troca: usar variavel auxiliar.
      escreva("O valor de A é ",a," e o valor de B " ,b,".")
      

      
Fimalgoritmo